### ISSUE TITLE
感谢，终于在 linux 上也能找到一款跟打器了

### ISSUE THREAD

**Issue by zangwill** [zhenyangze/wubigendaqi#2]
之前谷歌了好久，奇怪为什么没有找到这个，附一下在 Fedora 27 上的安装过程：
```bash
sudo dnf install qt5-devel
/usr/lib64/qt5/bin/qmake
make
./wubigendaqi
```
然后问题是无法调整界面大小，相对于屏幕来讲有点小了，请问有什么解决办法吗？

**Comment by leexuanhe** [comment]
还有一个问题是跟打文本比较多时，不会自动往下滚动。
源代码已经在这了，找本qt的书对着修改吧

**Comment by zhenyangze** [comment]
@Zangwill 
不好意思，最近有点忙，没注意到。
我暂时在笔记本上开发的，大屏幕尺寸没有测试。如果希望修改尺寸的话，可以把界面锁定关闭，然后打开软件后鼠标放大。

**Comment by zhenyangze** [comment]
@leexuanhe 软件制作时没有考虑跟进滚动的效果，在选择文本的时候，可以限制展示字数。
